### ISSUE TITLE
Išraše nerodo koordinačių prie hidroelektrinių

### ISSUE THREAD

**Issue by ambrazasp** [AplinkosMinisterija/biip-uetk-api#55]
Pagrindinių duomenų išraše nėra įrašomos kooordinatės, nors sistemoje jos yra:

https://admin.biip.lt/uetk/duomenu-gavimas/152

PS. Staginge negaliu patikrinti ar tas pats yra ir išplėstinių duomenų išrašuose, nes sugeneravus išrašą peržiūrint pdf rašo, kad įvyko klaida.
![Image](https://github.com/AplinkosMinisterija/biip-uetk-api/assets/102528051/6ccaf868-f7f7-496e-909b-9fa91139dc83)

**Comment by LWangllix** [comment]
![image](https://github.com/user-attachments/assets/9453db1e-ffb1-469a-a9d2-859c1915b278)
kaip ir yra
