### ISSUE TITLE
Išplėstiniuose išrašuose turi būti Vandens pertekliaus pralaidų atstumai nuo upės žiočių ir pastatymo metai

### ISSUE THREAD

**Issue by ambrazasp** [AplinkosMinisterija/biip-uetk-api#57]
Išplėstiniuose išrašuose prie vandens pertekliaus pralaidos turi būti eilutės:

Atstumas nuo upės žiočių 
Pastatymo metai 

![Image](https://github.com/AplinkosMinisterija/biip-uetk-api/assets/102528051/7c61013d-f9ce-46ee-8ee8-1648c29e5ec5)

**Comment by LWangllix** [comment]
Viskas veikia
